name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.pnpm-cache.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Cache pnpm store
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Restore dependencies
        if: needs.setup.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile --ignore-scripts
      - run: pnpm run build

  linter:
    needs: [setup, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Restore dependencies
        if: needs.setup.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile --ignore-scripts
      - run: pnpm run lint
      - run: pnpm run check

  tests:
    needs: [setup, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Restore dependencies
        if: needs.setup.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile --ignore-scripts
      - run: pnpm run test
